name: Pelican CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build the site
        run: docker compose run --rm pelican
        env:
          GDRIVE_DOCUMENT_ID: ${{ secrets.GDRIVE_DOCUMENT_ID }}
          GDRIVE_SHEET_ID: ${{ secrets.GDRIVE_SHEET_ID }}

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          cname: vzmsh.math-vsu.ru
